services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "11880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - influxdb2

  influxdb2:
    image: influxdb:latest
    container_name: influxdb2
    # restart: on-failure
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=6[z4AGvB5Tl35Y^2
      - DOCKER_INFLUXDB_INIT_ORG=sgh
      - DOCKER_INFLUXDB_INIT_BUCKET=aeroponics
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
