services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    restart: always

  influxdb:
    container_name: influxDB
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=
      - DOCKER_INFLUXDB_INIT_PASSWORD=
      - DOCKER_INFLUXDB_INIT_ORG=
      - DOCKER_INFLUXDB_INIT_BUCKET=
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
